/* Main.c file generated by New Project wizard
 *
 * Created:   Wed Nov 20 2019
 * Processor: MSP430G2553
 * Compiler:  CodeComposer for MSP430
 */

#include <msp430g2553.h>
//#include "lcdLib.c"
//#include "lcdLib.h"
#define EN		BIT4
#define RS		BIT5
#define DATA	0x0F
#include <msp430.h>
#define delay_ms(x)		__delay_cycles((long) x* 1000)
#define delay_us(x)		__delay_cycles((long) x)

void main()
 { 
   


   // Write your code here
    P1DIR |= 0b11100000;
     P2DIR |= 0b11111111;
    //P1OUT |=  BIT6 + BIT5 + BIT7;  
    
    P1REN |= (BIT0|BIT1|BIT2|BIT3);
        P1OUT |= (BIT0|BIT1|BIT2|BIT3);
        P1IES &= ~(BIT0|BIT1|BIT2|BIT3);
        P1IE |= (BIT0|BIT1|BIT2|BIT3);
        P1IFG &= ~(BIT0|BIT1|BIT2|BIT3);
    
    
    
    _enable_interrupt();
    
    
   while (1){
      P1OUT ^= BIT5;
      delay_ms(5);	
      P1OUT ^= BIT5;
      P1OUT ^= BIT6;
      delay_ms(5);	
      P1OUT ^= BIT6;
      P1OUT ^= BIT7;
      delay_ms(5);
      P1OUT ^= BIT7;
      }
      ;
 }
#pragma vector = PORT1_VECTOR
__interrupt void Port1_isr(void){
   //FIRST ROW OF KEYS
	if(P1IFG & BIT1){
	   if(P1OUT & BIT5){
	      //PRINT H ON LCD
	       WDTCTL = WDTPW + WDTHOLD;// Stop Watchdog
   delay_ms(100);
   P2DIR = EN + RS + DATA; 
   P2OUT = 0x02;
   P2OUT |= EN;
   P2OUT &= ~EN;
   delay_ms(5);
   P2OUT &= ~RS; // Set RS to Data
   P2OUT = 0x00;// Upper nibble
   P2OUT |= EN;
   P2OUT &= ~EN;
   P2OUT = 0x0E;
   P2OUT |= EN;
   P2OUT &= ~EN;
   delay_ms(5);
   P2OUT &= ~RS; // Set RS to Data
   P2OUT = 0x00;// Lower nibble
   P2OUT |= EN;
   P2OUT &= ~EN;
   P2OUT = 0x06;
   P2OUT |= EN;
   P2OUT &= ~EN;
   delay_ms(5);
  // P2OUT = 0x00;
 //  P2OUT |= RS;
   P2OUT = 0x24;
   P2OUT |= EN;
   P2OUT &= ~EN;
    //P2OUT = 0x00;
   //P2OUT |= RS;
   P2OUT = 0x28;
   P2OUT |= EN;
   P2OUT &= ~EN;
   delay_ms(5);
   
  

	      }
	   else if(P1OUT & BIT6){
	      P2OUT ^= BIT1;
	      
	      }
	   else if(P1OUT & BIT7){
	      P2OUT ^= BIT2;
	      }
	}
	//SECOND ROW OF KEYS
	if(P1IFG & BIT0){
	 if(P1OUT & BIT5){
	    P2OUT ^= BIT3;
	    }
	     else if(P1OUT & BIT6){
	      P2OUT ^= BIT4;
	      }
	      else if(P1OUT & BIT7){
	      P2OUT ^= BIT5;
	      }
	    
	   }
	   //THIRD ROW OF KEYS
	   if(P1IFG & BIT2){
	      if(P1OUT & BIT5){
		 P2OUT ^= BIT0;
		 }
	      else if(P1OUT & BIT6){
		 P2OUT ^= BIT4;
		 }
	      else if(P1OUT & BIT7){
		 P2OUT ^= BIT5;
		 }
	}
	//FOURTH ROW OF KEYS
	 if(P1IFG & BIT3){
	      if(P1OUT & BIT5){
		 P2OUT ^= BIT0;
		 }
	      else if(P1OUT & BIT6){
		 P2OUT ^= BIT4;
		 }
	      else if(P1OUT & BIT7){
		 P2OUT ^= BIT5;
		 }
	}
	P1IFG &= ~(BIT0|BIT1|BIT2|BIT3);

}

